### ISSUE TITLE
Suggestion: Save player's AFK status in their file

### ISSUE THREAD

**Issue by lukec11** [ifvictr/HCCore#31]
This way bots like [Hack Club's Minecraft Bot](https://github.com/lukec11/slack-commands) would be able to read the status, and display it in the command output

**Comment by ifvictr** [comment]
I don't feel like it's necessary since a certain player's AFK status would likely be more relevant to those who are actually playing on the server than those who are not. AFK currently works the way it is because it's per-session and it doesn't make sense to persist the status across sessions.

**Comment by ifvictr** [comment]
@lukec11 I don't feel like it's necessary since a certain player's AFK status would likely be more relevant to those who are actually playing on the server than those who are not. AFK currently works the way it is because it's per-session and it doesn't make sense to persist the status across sessions.
